# Generated by Django 2.2.7 on 2019-11-06 02:42

from django.db import migrations, models
import mmorpg.backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('race', models.CharField(choices=[(mmorpg.backend.models.Race('elf'), 'ELF'), (mmorpg.backend.models.Race('dwarf'), 'DWARF'), (mmorpg.backend.models.Race('human'), 'HUMAN'), (mmorpg.backend.models.Race('hobbit'), 'HOBBIT')], max_length=6)),
            ],
            options={
                'db_table': 'mmo_character',
            },
        ),
    ]
