# Generated by Django 2.2.7 on 2019-11-06 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mmorpg.backend.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.CharField(choices=[(mmorpg.backend.models.CharacterClass('fighter'), 'FIGHTER'), (mmorpg.backend.models.CharacterClass('rogue'), 'ROGUE'), (mmorpg.backend.models.CharacterClass('wizard'), 'WIZARD')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='sprite',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
