# Generated by Django 2.2.7 on 2019-11-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191106_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='char_class',
            new_name='character_class',
        ),
    ]
