# Generated by Django 2.2.7 on 2019-11-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191106_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='sprite',
            new_name='sprite_sheet',
        ),
        migrations.AddField(
            model_name='character',
            name='animations',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
