# Generated by Django 2.2.7 on 2019-11-27 17:39

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191127_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='animations',
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sprite_sheet',
        ),
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('elf', 'ELF'), ('dwarf', 'DWARF'), ('human', 'HUMAN'), ('hobbit', 'HOBBIT')], max_length=6)),
                ('character_class', models.CharField(choices=[('fighter', 'FIGHTER'), ('rogue', 'ROGUE'), ('wizard', 'WIZARD')], max_length=7)),
                ('animations', django_mysql.models.JSONField(default=dict)),
                ('sprite_sheet', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'mmo_character_template',
                'unique_together': {('race', 'character_class')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='template',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='backend.CharacterTemplate'),
            preserve_default=False,
        ),
    ]
