# Generated by Django 2.2.7 on 2019-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191127_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertemplate',
            name='character_class',
            field=models.CharField(choices=[('fighter', 'FIGHTER'), ('rogue', 'ROGUE'), ('wizard', 'WIZARD')], max_length=8),
        ),
    ]
